### PR TITLE
Remade `poll` command

### PR DESCRIPTION
**Pull request by lineargraph**
Remade the `poll` command:

 - Linq-ified a bit
 - refactored variable names
 - Added mentions as well as nicknames to the embeds.

THIS IS UNTESTED SINCE I DO NOT HAVE ACCESS TO A GUILD WITH THE NECESSARY ROLES + CHANNELS!

### CODE REVIEW

**Comment by HurricanKai** [comment]
Thats *not* how .Select works.

**Comment by lineargraph** [comment]
its not? oh well. i just thought https://msdn.microsoft.com/en-us/library/bb548891(v=vs.110).aspx

**Comment by lineargraph** [comment]
that should have fixed it

**Comment by HurricanKai** [comment]
@romangraef yeah, i know, thought, .select has some ... problems, but thanks a lot.

**Comment by HurricanKai** [comment]
forgot close != Merge

**Pull request merged**
